### ISSUE TITLE
missing prvReadpavelkh_Interest privilege

### ISSUE THREAD

**Issue by rvtria** [khorozhansky/Advanced-MultiSelect-for-Dynamics#3]
*SOLVED*

Hi Pavel,

first of all great job with the multiselect. 
I am new to dynamics and got assigned system admin for my company. We are using dynamics onPremise v8.2.

I added a multiselect according to your step-by-step tutorial and for me it worked perfectly.

However my colleague who has a different role gets the following error:

Error: An error occurred in the AdvancedMultiSelect.Plugins.ItemSet.GetItemSet plug-in. Exception: Principal user (Id=91c66c38-c873-e811-9103-005056b218e8, type=8) is missing prvReadpavelkh_Interest privilege (Id=1d29aeb1-2135-42fc-a072-d91b4743a71b) 

I tried allowing Read permission for the role (see below), however to no avail. I must have missed something.

![20180810_dynamics_multiselect_privileges](https://user-images.githubusercontent.com/42265189/43946045-5d2cf390-9c84-11e8-9dfa-d7ee24904524.png)

Can you please help me?

*EDIT:

I just found my mistake.
Instead of granting read privileges for the entity "AdvancedMultiSelect Item Set Configuration" I had to grant read privileges to Entity "Interest".

**Comment by khorozhansky** [comment]
Hi, and just in case, if you also would like the user to be able to edit the checkboxes then you might need to care about other permissions like "append to".
