### ISSUE TITLE
V9 App issue

### ISSUE THREAD

**Issue by ghost** [khorozhansky/Advanced-MultiSelect-for-Dynamics#4]
In v9 unified interface, we face the issue stated here when creating a new record: 
![image](https://user-images.githubusercontent.com/44158508/46939286-39d06380-d066-11e8-9e71-b6fd946f739e.png)

**Comment by khorozhansky** [comment]
Sorry for a late reply, does it work in Web UI?

**Comment by ghost** [comment]
> Sorry for a late reply, does it work in Web UI?

It does yes, sorry for my late answer...

**Comment by khorozhansky** [comment]
I'll look at it in about 2 weeks.

**Comment by ghost** [comment]
Hi, any updates on this bug? Thanks

**Comment by khorozhansky** [comment]
Hi, sorry for the late reply. I've just tried this scenario in UCI and reproduced the issue. 
Now In UCI, the system passes params to WebResource in a bit another way for a new record.
I'll fix the issue today and let you know.

**Comment by khorozhansky** [comment]
Hello, the issue should be fixed now, please try to download the solution from the latest release. (https://github.com/khorozhansky/Advanced-MultiSelect-for-Dynamics/releases/latest)
Please let me know if any question.

**Comment by ghost** [comment]
Many thanks dude, awesome work!
