### ISSUE TITLE
Multiselect work in IE not in Chrome

### ISSUE THREAD

**Issue by LiftEmotion** [khorozhansky/Advanced-MultiSelect-for-Dynamics#5]
Hi,
I have loaded the solution into CRM365 on premise. 
I have put it on the account form. During installation and setting it up I used IE during the tests it works fine - now I checked it in Chrome and now it doens't work any more and I can't acces the accounts any more through Chrome - states record not available. 
See error message below - Sorry it is in Dutch

![2019-05-06_16h19_40](https://user-images.githubusercontent.com/50330173/57231457-d2d2c600-701a-11e9-9db9-d6dd597f46b2.jpg)

When I download the error message I get....

Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: System.Web.HttpUnhandledException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #30132D79Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>0a3d97af-6b19-4256-ae65-5c92bc6812a0</ActivityId>
  <ErrorCode>-2147220970</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>System.Web.HttpUnhandledException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #30132D79</Message>
  <Timestamp>2019-05-06T13:55:47.2416237Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>0a3d97af-6b19-4256-ae65-5c92bc6812a0</ActivityId>
    <ErrorCode>-2147220969</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>systemform With Id = 70a85103-2444-4d16-a543-0b1a7b96ab88 Does Not Exist</Message>
    <Timestamp>2019-05-06T13:55:47.2416237Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault i:nil="true" />
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
What can I do to solve this problem?

Looking forward to your reply.

**Comment by khorozhansky** [comment]
Hi, that's a bit strange, are you still able to open the account form in IE?

**Comment by khorozhansky** [comment]
Do you get this message when you open an account or when you save it?

**Comment by LiftEmotion** [comment]
Hi Pavel,
I get this message when I trie to open the record - only in Chrome. 
I can still open the account records in IE.
ANother strange thing is that on a clean PC I have tested it and there the accounts work in IE and in Chroma as well - strange.

**Comment by khorozhansky** [comment]
In Chrome, try to clean up the cache, or press F12 and then right mouse click on the reload button:
![image](https://user-images.githubusercontent.com/5520921/57237491-feac7680-702f-11e9-9467-e2375ebe806a.png)

**Comment by LiftEmotion** [comment]
Hi Pavel,

Unfortunately doesn't have any effect. Still got the error...
I can go up to the overview of the records - when select one to open the error occurs.

![2019-05-06_18h29_34](https://user-images.githubusercontent.com/50330173/57239739-09b1d780-702d-11e9-9604-9bcc8ada109a.jpg)

Any other suggestion?

Regards
Rene

**Comment by khorozhansky** [comment]
If I'm not mistaken the error like this sometimes may appear if you had some form for an entity, used it to view the record last time and then deleted the form. In such a case, when you try to open the record the system tries to use the last used form even though it does not exist anymore. It's an issue in CRM itself. I cannot recollect how to resolve but try to log out and clear local storage: 
In the chrome console: localStorage.clear()

**Comment by LiftEmotion** [comment]
Hi Paval,
That did the trick - I did as you described and it works.
Thank you for your help.

**Comment by khorozhansky** [comment]
Great, have a nice day!
